#!/usr/bin/env python3
"""Stage 7 — sound effects and room tone, from ElevenLabs.

Room tone is the one layer that must never be absent: absolute digital silence
under a found recording destroys the illusion that anything was recorded at
all. Everything here is listed in the episode's audio.yaml under `sfx:` so a
lost file is regenerable from the repository.

Usage: gen_sfx.py [episode dir] [--only wind]
"""
import json, os, pathlib, sys, urllib.request, yaml

print = __import__('functools').partial(print, flush=True)
API = "https://api.elevenlabs.io/v1/sound-generation"


def env():
    for line in pathlib.Path(".env").read_text().splitlines():
        if "=" in line and not line.strip().startswith("#"):
            k, v = line.split("=", 1); os.environ.setdefault(k.strip(), v.strip())


def main():
    env()
    args = sys.argv[1:]
    only = None
    if "--only" in args:
        i = args.index("--only"); only = args[i + 1]; del args[i:i + 2]
    ep = pathlib.Path(args[0] if args else "episodes/ep-02-sunrise-line")
    cfg = yaml.safe_load((ep / "audio.yaml").read_text())
    key = os.environ["ELEVENLABS_API_KEY"]

    # teaser_sfx is generated by the same call; it is separated in audio.yaml
    # only so the record's own bed and the promo bed cannot be confused for
    # each other when someone is looking for what runs under the episode.
    beds = {**(cfg.get("sfx") or {}), **(cfg.get("teaser_sfx") or {})}
    for name, spec in beds.items():
        if only and name != only:
            continue
        dest = ep / "audio" / spec["file"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists():
            print(f"  skip  {name} ({dest} already there)"); continue
        text = " ".join(spec["prompt"].split())
        # 450 is the API's hard limit and it is easy to pass without noticing:
        # a bed prompt is mostly a list of things that must not be in it, and
        # that list only ever grows. Checked here so the failure costs nothing.
        if len(text) > 450:
            print(f"  {name}: prompt is {len(text)} characters, the limit is 450")
            continue
        # Music goes to a different endpoint with a different body. It is in
        # this script because it is the same decision — a bed the episode
        # needs, generated rather than licensed, described in the episode's own
        # audio.yaml so a lost file is regenerable.
        if spec.get("kind") == "music":
            mb = {"prompt": text, "music_length_ms": int(spec.get("seconds", 30) * 1000)}
            rq = urllib.request.Request(
                "https://api.elevenlabs.io/v1/music", data=json.dumps(mb).encode(),
                headers={"xi-api-key": key, "Content-Type": "application/json"})
            try:
                dest.write_bytes(urllib.request.urlopen(rq, timeout=300).read())
            except urllib.error.HTTPError as e:
                print(f"  HTTP {e.code} on {name}\n"
                      f"    {e.read()[:400].decode(errors='replace')}")
                raise
            print(f"  saved {name:<8} {dest}  ({dest.stat().st_size // 1024} KB)  music")
            continue

        body = {"text": text,
                "duration_seconds": spec.get("seconds", 22),
                "prompt_influence": spec.get("influence", 0.6)}
        r = urllib.request.Request(
            API, data=json.dumps(body).encode(),
            headers={"xi-api-key": key, "Content-Type": "application/json"})
        try:
            dest.write_bytes(urllib.request.urlopen(r, timeout=300).read())
        except urllib.error.HTTPError as e:
            # A bare "HTTP Error 400" says nothing about which field the API
            # rejected, and this script spends subscription characters. The
            # third script in this repository to need this; it is now in all
            # of them.
            print(f"  HTTP {e.code} on {name}\n"
                  f"    {e.read()[:400].decode(errors='replace')}\n"
                  f"    prompt was {len(body['text'])} characters")
            raise
        print(f"  saved {name:<8} {dest}  ({dest.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
